// <auto-generated />
namespace AutoDealerManager.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Fix2_cpf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix2_cpf));
        
        string IMigrationMetadata.Id
        {
            get { return "202412020559525_fix2_cpf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
