// <auto-generated />
namespace AutoDealerManager.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_numero_endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_numero_endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "202411102322069_add_numero_endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
